### ISSUE TITLE
Example application is down

### ISSUE THREAD

**Issue by vemv** [crosslandwa/node-push#2]
Hi!

Ableton Push mk I owner here, I'd love to quickly evaluate how the library works. However the example app is down.

It'd be great if you hosted it again!

Cheers - Victor

**Comment by vemv** [comment]
I could build and run https://github.com/crosslandwa/push-wrapper-example-site locally - it works!

So no biggie as far I am concerned.

**Comment by crosslandwa** [comment]
Fixed link to hosted example app here:
https://github.com/crosslandwa/push-wrapper/commit/5463cf6a46ab837d9ebc5841cc8041f34d7cb634
